set(CMAKE_SYSTEM_NAME  Linux)
set(CMAKE_C_COMPILER   i686-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER i686-linux-gnu-g++)
set(CMAKE_C_FLAGS      "-m32 -march=i386")
set(CMAKE_CXX_FLAGS    "-m32 -march=i386")