set(CMAKE_SYSTEM_NAME  Linux)
set(CMAKE_C_COMPILER   aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
set(CMAKE_C_FLAGS      "-march=armv8-a")
set(CMAKE_CXX_FLAGS    "-march=armv8-a")