set(CMAKE_SYSTEM_NAME  Windows)
set(CMAKE_C_COMPILER   /clangarm64/bin/clang)
set(CMAKE_CXX_COMPILER /clangarm64/bin/clang++)
set(CMAKE_C_FLAGS      "-march=armv8-a")
set(CMAKE_CXX_FLAGS    "-march=armv8-a")