/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_lukebemish_opensesame_natives_NativeImplementations */

#ifndef _Included_dev_lukebemish_opensesame_natives_NativeImplementations
#define _Included_dev_lukebemish_opensesame_natives_NativeImplementations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_lukebemish_opensesame_natives_NativeImplementations
 * Method:    nativeImplLookup
 * Signature: ()Ljava/lang/invoke/MethodHandles/Lookup;
 */
JNIEXPORT jobject JNICALL Java_dev_lukebemish_opensesame_natives_NativeImplementations_nativeImplLookup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
