{
    "name": "Build PR",
    "concurrency": "ci-${{ github.ref }}",
    "on": {
        "pull_request": {
            
        }
    },
    "jobs": {
        "build": {
            "runs-on": "ubuntu-22.04",
            "steps": [
                {
                    "name": "Setup Java",
                    "run": "echo \"JAVA_HOME=$JAVA_HOME_21_X64\" >> \"$GITHUB_ENV\""
                },
                {
                    "name": "Checkout",
                    "uses": "actions/checkout@v4",
                    "with": {
                        "fetch-depth": "0",
                        "persist-credentials": "false"
                    }
                },
                {
                    "name": "Validate Gradle Wrapper",
                    "uses": "gradle/actions/wrapper-validation@v5"
                },
                {
                    "name": "Cache",
                    "uses": "actions/cache/restore@v4",
                    "with": {
                        "path": "**/.gradle/loom-cache\n**/.gradle/quilt-loom-cache",
                        "key": "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}",
                        "restore-keys": "${{ runner.os }}-gradle-"
                    }
                },
                {
                    "name": "Setup Gradle",
                    "uses": "gradle/actions/setup-gradle@v4",
                    "with": {
                        "cache-read-only": true,
                        "gradle-home-cache-cleanup": true
                    }
                },
                {
                    "name": "Publish",
                    "id": "publish",
                    "run": "./gradlew publish",
                    "env": {
                        "PR_NUMBER": "${{ github.event.pull_request.number }}"
                    }
                },
                {
                    "name": "Archive Publishable Artifacts",
                    "uses": "actions/upload-artifact@v4",
                    "with": {
                        "name": "artifacts",
                        "path": "build/repo"
                    }
                }
            ]
        }
    }
}