name: Build Natives
on:
  push:
    branches:
      - natives
jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: [build-natives]
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - run: ./gradlew publish -Pcommit_sha=${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

